#!/usr/bin /env bash
# Display formatted information from /etc/passwd using while + IFS

while IFS=':' read -r username password uid gid info home shell; do
  echo "The user $username is part of the $gid gang, lives in $home and rides $shell. User ID's place is protected by the passcode $password, more info about the user here: $info"
done < /etc/passwd
