#!/usr/bin/env bash
#the comment
i=1
while [ \$i -le 20 ]; do
  case \$i in
    4)
      echo "\$i and then bad luck from China"
      ;;
    9)
      echo "\$i and then bad luck from Japan"
      ;;
    17)
      echo "\$i and then bad luck from Italy"
      ;;
    *)
      echo "\$i"
      ;;
  esac
  i=$((i + 1))
done
