#!/usr/bin/env bash
#the comment
i+1

while [ "$i" -le 20]
do 
	echo "$i"
	  
	case "$1" in
		4) 
			echo "bad luck from china"
			;;
		9)
			echo "bad luck from japan"
			;;
		17)	
			echo "bad luck from Italy"
			;;
	esac
	
	i=$((i + 1))
 done	
