#!/usr/bin/env bash
#comment
PID_FILE="/var/run/myscript.pid"

cleanup() {
    echo "Deleting $PID_FILE and terminating."
    rm -f "$PID_FILE"
    exit 0
}

trap 'echo "I hate the kill command"; cleanup' SIGTERM
trap 'echo "Y U no love me?!";' SIGINT
trap 'cleanup' SIGQUIT

echo $$ > "$PID_FILE"

while true; do
    echo "To infinity and beyond"
    sleep 1
done
